### PR TITLE
Android deeplink support (send notifications with URI on Android devices)

### PR DESCRIPTION
**Pull request by mirzemehdi**
Solves: https://github.com/mirzemehdi/KMPNotifier/issues/52

In order to setData for URI on Android Devices, you just need to put data with "URL" key into payloadData (after converting URI toString)

Example code:
```kotlin

//Notifier.KEY_URL value is set as "URL" in the library. If payload data contains that key, then its value will be set as intent data.

notifier.notify(
    title = "Title", 
    body = "bodyMessage", 
    payloadData = mapOf(
        Notifier.KEY_URL to "https://github.com/mirzemehdi/KMPNotifier/",
        "extraKey" to "randomValue"
    )
)

```

### CODE REVIEW

**Comment by estreteca** [comment]
How can I capture the notification when the app is closed?, and thus be able to refresh cache for example

**Comment by RomanMarinov** [comment]
how to catch a push notification click if the application was previously destroyed? I want to open another activity

**Comment by akinkhov** [comment]
where to process a push if the application is closed?

**Comment by ubarua123** [comment]
This library does not work when the app is killed/closed. Only works when it's in foreground. Took me a while to figure this out.

**Comment by mirzemehdi** [comment]
@ubarua123 that's not true completely. Well both yes, and no

On Android this is how it works:

If you send both notification and data type message, or just notification type message, then you are right when app is in background listener will not be called.

If you want listener to be called when app is in background or killed, you need to send only data type message, that way listener will be called when app is in background. This is how it works from Firebase side. When you try to test push notificaiton from firebase console it will attach notification type message. So solution would be sending push notification using api, and sending only data type message.

You can use this file to test your notification and in the script remove notification title, and body part and send only data type message:
https://github.com/mirzemehdi/KMPNotifier/blob/main/firebase_push_notification_sender.py


Related stackoverflow issue: https://stackoverflow.com/questions/37358462/firebase-onmessagereceived-not-called-when-app-in-background

From ios side I still need to investigate a bit : but you can check comments in this issue as well: https://github.com/mirzemehdi/KMPNotifier/issues/24

**Pull request merged**
